apiVersion: v1
kind: Secret
metadata:
  name: nanaconecta-backend-secret
  namespace: nanaconecta
  labels:
    app.kubernetes.io/name: nanaconecta-backend
type: Opaque
stringData:
  DATABASE_URL: "postgresql://nana_user:REEMPLAZAR_PASSWORD@postgres-service:5432/nanaconecta_db"
  JWT_SECRET: "REEMPLAZAR_CON_SECRETO_SEGURO"