apiVersion: v1
kind: Service
metadata:
  name: nanaconecta-backend-service
  namespace: nanaconecta
  labels:
    app.kubernetes.io/name: nanaconecta-backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: nanaconecta-backend
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP